export const FETCH_COCKTAIL_START = "FETCH_COCKTAIL_START";
export const FETCH_COCKTAIL_SUCCESS = "FETCH_COCKTAIL_SUCCESS";
export const FETCH_COCKTAIL_FAIL = "FETCH_COCKTAIL_FAIL";

export const GET_SINGLE_COCKTAIL_START = "GET_SINGLE_COCKTAIL_START";
export const GET_SINGLE_COCKTAIL_SUCCESS = "GET_SINGLE_COCKTAIL_SUCCESS";
export const GET_SINGLE_COCKTAIL_FAIL = "GET_SINGLE_COCKTAIL_FAIL";
